import { useState, useEffect, useRef } from 'react';

const stats = [
  {
    number: "80%",
    text: "of all B2B social leads drove by LinkedIn, the #1 platform for B2B growth."
  },
  {
    number: "82%",
    text: "of buyers trust companies whose founders are active online."
  },
  {
    number: "8x",
    text: "more engagement is generated by personal posts compared to company posts"
  },
  {
    number: "49%",
    text: "of a company's reputation is directly tied to its CEO"
  }
];

export default function LeverageSection() {
  const [visibleItems, setVisibleItems] = useState<number[]>([]);
  const itemRefs = useRef<(HTMLDivElement | null)[]>([]);
  const headerRef = useRef<HTMLDivElement | null>(null);
  const [headerVisible, setHeaderVisible] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.target === headerRef.current && entry.isIntersecting) {
            setHeaderVisible(true);
          } else if (entry.isIntersecting) {
            const index = itemRefs.current.indexOf(entry.target as HTMLDivElement);
            if (index !== -1 && !visibleItems.includes(index)) {
              setTimeout(() => {
                setVisibleItems(prev => [...prev, index]);
              }, index * 150);
            }
          }
        });
      },
      { threshold: 0.1, rootMargin: '0px 0px -50px 0px' }
    );

    if (headerRef.current) observer.observe(headerRef.current);

    setTimeout(() => {
      itemRefs.current.forEach((ref) => {
        if (ref) observer.observe(ref);
      });
    }, 100);

    return () => observer.disconnect();
  }, []);

  return (
    <div className="py-20 px-6">
      <div className="max-w-6xl mx-auto">
        <div ref={headerRef} className={`transition-all duration-700 ${
          headerVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
        }`}>
          <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4 text-center">
            Posting isn't just for likes, it's leverage.
          </h2>

          <p className="text-xl text-gray-600 text-center mb-12">
            Here's why founders can't afford to stay invisible:
          </p>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 max-w-6xl mx-auto">
          {stats.map((stat, index) => (
            <div
              key={index}
              ref={(el) => {itemRefs.current[index] = el}}
              className={`text-center transition-all duration-700 ${
                visibleItems.includes(index)
                  ? 'opacity-100 translate-y-0'
                  : 'opacity-0 translate-y-12'
              }`}
            >
              <div className="text-6xl md:text-7xl font-bold text-primary mb-3">
                {stat.number}
              </div>
              <p className="text-base text-gray-900">
                {stat.text}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}